_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "catalog://ImageNetPretrained/FAIR/R-50-GN"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    NORM: "GN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "GN"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "GN"
  ROI_HEADS:
    NUM_CLASSES: 352
  ROI_MASK_HEAD:
    NORM: "GN"
#SOLVER:
  # 3x schedule
#  STEPS: (210000, 250000)
#  MAX_ITER: 270000

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('openlogo_supervised_trainval',)
  TEST: ('openlogo_supervised_test',)
SOLVER:
#  MAX_ITER: 112000       # images: 18752 -> 1 GPU: 12 epochs --> 225.024 iters
#  STEPS: (75000, 95000)  # 8epochs - 10epochs
#  IMS_PER_BATCH: 2
#  BASE_LR: 0.0025

#  MAX_ITER: 55000       # images: 18752 -> 1 GPU: 12 epochs --> 225.024 iters
#  STEPS: (35000, 45000)  # 8epochs - 10epochs
#  IMS_PER_BATCH: 4
#  BASE_LR: 0.005

  MAX_ITER: 45000       # images: 18752 -> 1 GPU: 12 epochs --> 225.024 iters
  STEPS: (27000, 36000)  # 8epochs - 10epochs
  IMS_PER_BATCH: 16
  BASE_LR: 0.02

  WARMUP_ITERS: 2000

#OUTPUT_DIR: "./output"
#OUTPUT_DIR: "./output/openlogo/resnet50"
OUTPUT_DIR: "./output/openlogo/resnet50-gn-3x"
