_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res3,Res4,Res5
    DEFORM_MODULATED: False
  ROI_HEADS:
    NUM_CLASSES: 352

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('openlogo_supervised_trainval',)
  TEST: ('openlogo_supervised_test',)
SOLVER:
#  MAX_ITER: 112000       # images: 18752 -> 1 GPU: 12 epochs --> 225.024 iters
#  STEPS: (75000, 95000)  # 8epochs - 10epochs
#  IMS_PER_BATCH: 2
#  BASE_LR: 0.0025

#  MAX_ITER: 55000       # images: 18752 -> 1 GPU: 12 epochs --> 225.024 iters
#  STEPS: (35000, 45000)  # 8epochs - 10epochs
#  IMS_PER_BATCH: 4
#  BASE_LR: 0.005

  MAX_ITER: 15000       # images: 18752 -> 1 GPU: 12 epochs --> 225.024 iters
  STEPS: (9000, 12000)  # 8epochs - 10epochs
  IMS_PER_BATCH: 16
  BASE_LR: 0.02

  WARMUP_ITERS: 750

#OUTPUT_DIR: "./output"
#OUTPUT_DIR: "./output/openlogo/resnet50"
OUTPUT_DIR: "./output/openlogo/resnet50-dconv_c3-c5-1x"
